include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

variables:
  DEBIAN_FRONTEND: noninteractive
  DEPS_DEV: "libgirepository1.0-dev libglib2.0-dev libgtk-3-dev python-gi-dev libpwquality-dev python3-all python3-construct python3-dateutil python3-pycryptodome python3-pykeepass libhandy-1-dev python3-pwquality"
  DEPS_DEB: "git git-buildpackage appstream-util debhelper-compat dh-python meson"

stages:
  - Code Analysis
  - Build

cache:
    paths:
        - .apt

.before_script_template: &basic-deps
    before_script:
        - rm -f /etc/apt/apt.conf.d/docker-clean
        - mkdir -p .apt
        - apt-get -o dir::cache::archives=".apt" -qq update
        - apt-get -o dir::cache::archives=".apt" -qq install -y --no-install-recommends ${DEPS_DEV} -o=Dpkg::Use-Pty=0 flake8 pylint mypy > /dev/null

code_analysis:
    stage: Code Analysis
    <<: *basic-deps
    image: debian:sid
    script:
        - flake8 --max-line-length=170 --ignore=E402,W503 --show-source passwordsafe/
        - mypy --ignore-missing-imports --disallow-incomplete-defs passwordsafe/
        - pylint --rcfile=.pylintrc passwordsafe/*.py

flatpak:
    stage: Build
    image: registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master
    variables:
        APP_ID: org.gnome.PasswordSafeDevel
        MANIFEST_PATH: "flatpak/org.gnome.PasswordSafe.json"
        RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
        FLATPAK_MODULE: "passwordsafe"
        MESON_ARGS: "-Dprofile=development"
        BUNDLE: "org.gnome.PasswordSafeDevel.flatpak"
    extends: .flatpak

debian:
    stage: Build
    <<: *basic-deps
    image: debian:sid
    script:
        - apt-get -qq install -y --no-install-recommends -o dir::cache::archives=".apt" -o=Dpkg::Use-Pty=0 ${DEPS_DEB} > /dev/null
        - git config --global user.email "gitlab-ci@buildbot.org"
        - git config --global user.name "BuildBot @ gitlab-ci"
        - git remote add debianx https://salsa.debian.org/python-team/packages/gnome-passwordsafe.git
        - git fetch debianx
        - git checkout debian/master
        - gbp import-ref -uHEAD --upstream-branch=$CI_COMMIT_BRANCH --upstream-tag=origin/$CI_COMMIT_BRANCH
        - gbp dch -S --since=HEAD
        - sed -i "2iDEB_CONFIGURE_EXTRA_FLAGS = -Dprofile=development" debian/rules
        - echo -e "\noverride_dh_auto_configure:\n\tdh_auto_configure -- -Dprofile=development" >> debian/rules
        - dpkg-buildpackage -us -uc -b
        - mv ../gnome-passwordsafe*.deb ./gnome-passwordsafe_devel_${CI_COMMIT_TIMESTAMP}_git${CI_COMMIT_SHORT_SHA}_all.deb
    artifacts:
        name: 'DEB package artifacts'
        expose_as: 'Get Debian package here'
        when: 'always'
        paths:
                - "gnome-passwordsafe_devel_${CI_COMMIT_TIMESTAMP}_git${CI_COMMIT_SHORT_SHA}_all.deb"
